project:
  type: book
  output-dir: _book
  execute-dir: project

execute:
  freeze: auto

book:
  title: "Multispectral water stress monitoring"
  subtitle: "A tutorial and competition to estimate drought impacts on the light use efficiency of photosynthesis from multispectral remote sensing data."
  author: "Benjamin Stocker, Fabian Bernhard"
  date: "2025/12/02"
  page-navigation: true
  chapters:
    - index.qmd
    - context.qmd
    - exercises.qmd
    - references.qmd
  appendices:
    - appendix_config.qmd
  favicon: "figures/favicon.ico"
  twitter-card: true
  search: true
  repo-url: https://github.com/geco-bern/drought_predictors_competition/
  sharing: [twitter, facebook]
  navbar:
    title: " "
    logo: "images/logo.png"
    background: "#3A3A3A"
    search: true
    right:
      - text: "Home"
        file: index.qmd

bibliography: references.bib

format:
  html:
    mathjax: true
    theme: 
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
